import yfinance as yf
import pandas as pd
import datetime

def fetch_data(ticker, period="2y"):
    """
    Fetches historical stock data using Yahoo Finance.
    """
    try:
        stock = yf.Ticker(ticker)
        df = stock.history(period=period)
        if df.empty:
            return None
        
        # Reset index to make Date a column instead of index
        df = df.reset_index()
        # Clean column names just in case
        df.columns = [c.capitalize() for c in df.columns]
        
        # Forward fill missing values
        df = df.ffill()
        return df
    except Exception as e:
        print(f"Error fetching data: {e}")
        return None

def prepare_features_for_lr(df):
    """
    Prepares basic features for Linear Regression.
    """
    # Create simple features: previous day's close, 5-day MA
    df['Prev_Close'] = df['Close'].shift(1)
    df['MA_5'] = df['Close'].rolling(window=5).mean()
    df['MA_10'] = df['Close'].rolling(window=10).mean()
    
    # Drop rows with NaN values generated by shifting/rolling
    df = df.dropna()
    return df
