import yfinance as yf
import pandas as pd
import datetime
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

def fetch_data(ticker, period="2y"):
    """
    Fetches historical stock data using Yahoo Finance.
    """
    try:
        stock = yf.Ticker(ticker)
        df = stock.history(period=period)
        if df.empty:
            return None
        
        # Reset index to make Date a column instead of index
        df = df.reset_index()
        # Clean column names just in case
        df.columns = [c.capitalize() for c in df.columns]
        
        # Forward fill missing values
        df = df.ffill()
        return df
    except Exception as e:
        print(f"Error fetching data: {e}")
        return None

def prepare_features_for_lr(df):
    """
    Prepares basic features for Linear Regression.
    """
    # Create simple features: previous day's close, 5-day MA
    df['Prev_Close'] = df['Close'].shift(1)
    df['MA_5'] = df['Close'].rolling(window=5).mean()
    df['MA_10'] = df['Close'].rolling(window=10).mean()
    
    # Drop rows with NaN values generated by shifting/rolling
    df = df.dropna()
    return df

def fetch_news_sentiment(ticker):
    """
    Fetches latest news for a ticker and calculates average sentiment.
    Returns: (average_score, list_of_news_dict)
    """
    try:
        stock = yf.Ticker(ticker)
        news = stock.news
        if not news:
            return 0.0, []
            
        analyzer = SentimentIntensityAnalyzer()
        total_score = 0
        analyzed_news = []
        
        for article in news[:5]: # max 5 items
            title = article.get('title', '')
            score = analyzer.polarity_scores(title)['compound']
            total_score += score
            analyzed_news.append({
                'title': title,
                'link': article.get('link', '#'),
                'publisher': article.get('publisher', 'Unknown'),
                'score': score
            })
            
        avg_score = total_score / len(analyzed_news) if analyzed_news else 0.0
        return avg_score, analyzed_news
    except Exception as e:
        print(f"Error fetching news sentiment: {e}")
        return 0.0, []

def fetch_realtime_price(ticker):
    """
    Fetches the latest real-time price.
    """
    try:
        df = yf.download(ticker, period='1d', interval='1m', progress=False)
        if not df.empty:
            # Depending on yfinance version, columns could be MultiIndex
            if isinstance(df.columns, pd.MultiIndex):
                return float(df['Close'][ticker].iloc[-1])
            return float(df['Close'].iloc[-1])
    except Exception as e:
        print(f"Error fetching realtime: {e}")
    return None
